export interface Programme {
  id: string;
  slug: string;
  title: string;
  code: string;
  project: string;
  image: string;
  credentials: string[];
}

export const programmes: Programme[] = [
  {
    id: "a29219f6-3563-4715-bd02-29cd5ea48bdf",
    slug: "mp1",
    title: "Sustainable Energy Technologies and Strategies in Urban Environments",
    code: "MP1",
    project: "RES4CITY",
    image: "/images/mp1.jpg",
    credentials: [
      "Fundamentals of Energy Systems",
      "Introduction to Renewable Energies",
      "Introduction to Sustainable Finance",
      "Data Analytics for the Energy Sector",
      "Efficient Building Techniques",
      "Tools for City Decarbonisation",
      "Energy Utilisation and Storage",
      "Case Studies in Energy Management",
      "Energy Policy and Flexible Technologies",
      "Serious Game",
    ],
  },
  {
    id: "3a94b30f-327f-4bc9-ad4a-2211b8328056",
    slug: "mp2",
    title: "Decarbonization Strategies and Social Innovation for Cities and Communities",
    code: "MP2",
    project: "RES4CITY",
    image: "/images/mp2.jpg",
    credentials: [
      "Fundamentals of Energy Systems",
      "Introduction to Renewable Energies",
      "Introduction to Sustainable Finance",
      "Sustainable Business Models",
      "Energy Strategy and Energy Transition",
      "Social Acceptance of Technologies",
      "Energy Communities",
      "Sustainable Development Goals for Cities",
      "Circular Economy for Sustainable Cities",
      "Serious Game",
    ],
  },
  {
    id: "da46bcc5-008f-49ab-84ba-102f66cbd7b0",
    slug: "mp3",
    title: "Advanced Design of Sustainable Cities",
    code: "MP3",
    project: "RES4CITY",
    image: "/images/mp3.jpg",
    credentials: [
      "Introduction to Sustainable Finance",
      "Data Analytics for the Energy Sector",
      "Energy Management and Smart Communities",
      "Decarbonisation of Thermal Energy",
      "Analysis of Energy Consumption",
      "Advanced Modelling of Buildings and Energy Systems",
      "Economics and Physics of Energy Storage",
      "Biogas Systems for Climate Transition",
      "Small Scale Wind Power",
      "Serious Game",
    ],
  },
  {
    id: "ca9c4d3f-1540-46b1-955f-b57163377987",
    slug: "mp4",
    title: "Business Strategies for a Sustainable Urban Transition",
    code: "MP4",
    project: "RES4CITY",
    image: "/images/mp4.jpg",
    credentials: [
      "Introduction to Renewable Energies",
      "Tools, Strategies and Trends in Sustainable Finance",
      "Circular Economy for Sustainable Cities",
      "Sustainable Business Models",
      "Energy Strategy and Energy Transition",
      "Urban Renewable Energy: Decision Making Methodologies",
      "Management of Innovation Projects",
      "Strategic Behaviour in Energy Markets: Options and Games",
      "Climate Risk and Climate Investing",
      "Serious Game",
    ],
  },
  {
    id: "bc929274-01b2-4687-a38c-a9d61bba607f",
    slug: "mp5",
    title: "Sustainability by Design: Developing a Resilient Built Environment",
    code: "MP5",
    project: "RES4CITY",
    image: "/images/mp5.jpg",
    credentials: [
      "Efficient Building Techniques",
      "Thermal Simulation of Buildings",
      "Understanding Critical Raw Materials",
      "Urban Metabolism Strategies",
      "Renewable Energy Investments",
      "Tools for City Decarbonisation",
      "Advanced Modelling of Buildings and Energy Systems",
      "Hydrogen Technologies for Urban Areas",
      "Positive Energy Districts",
      "Serious Game",
    ],
  },
  {
    id: "a4611b4e-caa4-4012-8962-b9f4d5629b0d",
    slug: "mp6",
    title: "Innovation in the Urban Energy Sector: Strategies and Management",
    code: "MP6",
    project: "RES4CITY",
    image: "/images/mp6.jpg",
    credentials: [
      "Introduction to Renewable Energies",
      "Decision-Making for Energy Projects under Uncertainty",
      "Management of Innovation Projects",
      "Social Acceptance of Technologies",
      "Renewable Energy Investments",
      "Sustainable Business Models",
      "Energy Justice and Poverty",
      "Gender Mainstreaming and Intersectionality",
      "Data Analytics for the Energy Sector",
      "Serious Game",
    ],
  },
  {
    id: "1b7abbbe-ef14-45f4-9dce-92f92090c297",
    slug: "mp7",
    title: "Sustainable Energy Solutions for Cities: Policy and Implementation Strategies",
    code: "MP7",
    project: "RES4CITY",
    image: "/images/mp7.jpg",
    credentials: [
      "Introduction to Renewable Energies",
      "Energy Policy",
      "Energy Strategy and Energy Transition",
      "How Sustainable is your City?",
      "Energy Justice and Poverty",
      "Social Acceptance of Technologies",
      "Digital Payments and Smart City Platforms",
      "Enacting a Circular Economy",
      "Sustainable Business Models",
      "Serious Game",
    ],
  },
  {
    id: "6aa09c6c-484c-43a0-97fa-1cc0ec58ca07",
    slug: "mp8",
    title: "Sustainable Finance and Energy Transition in Cities",
    code: "MP8",
    project: "RES4CITY",
    image: "/images/mp8.jpg",
    credentials: [
      "Introduction to Renewable Energies",
      "Urban Renewable Energy: Decision Making Methodologies",
      "Tools, Strategies and Trends in Sustainable Finance",
      "Investing in Sustainability",
      "Introduction to Industrial Organization",
      "Energy Markets",
      "Digital Payments and Smart City Platforms",
      "How Sustainable is your City?",
      "Climate Risk and Climate Investing",
      "Serious Game",
    ],
  },
  {
    id: "c95ce00f-8204-4f6c-9281-b92097256464",
    slug: "mp01sher",
    title: "Building Energy Renovation Financing",
    code: "MP01",
    project: "SHERLOCK",
    image: "/images/mp01sher.jpg",
    credentials: [
      "Basics of Energy Efficiency",
      "Decision-making towards a Sustainable City",
      "Environmental Social Governance Finance",
      "Advertising and Public Relations in the Energy Sector",
      "Systemic Design For Energy Retrofitting",
      "Green Infrastructure Finance",
      "Communication Strategies with Financial Institutions",
      "Business Model for Energy Efficiency in Buildings",
      "Energy Performance Contracting (EPC)",
      "Probabilistic Approach for Energy Efficiency Evaluation",
    ],
  },
  {
    id: "581037c4-ff3e-46f2-bb9e-d6305e8e168d",
    slug: "mp02sher",
    title: "Energy Efficiency in the Building Sector",
    code: "MP02",
    project: "SHERLOCK",
    image: "/images/mp02sher.jpg",
    credentials: [
      "Basics of Energy Efficiency",
      "Decision-making towards a Sustainable City",
      "Environmental Social Governance Finance",
      "Advertising and Public Relations in the Energy Sector",
      "Systemic Design For Energy Retrofitting",
      "Energy Auditing of Buildings",
      "Incorporation of Natural Materials in Energy Renovation of Buildings",
      "Life Cycle Analysis in Construction",
      "Circular Economy in the Built Environment",
      "Energy Consumption in Buildings",
    ],
  },
];
